version: '2'

run:
  timeout: 3m
  tests: true

linters:
  enable:
    - errcheck
    - errorlint
    - errname
    - nilerr
    - wrapcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    errcheck:
      exclude-functions:
        - 'fmt.Fprintf'
        - 'fmt.Fprintln'

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
