services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - GOPROXY=https://proxy.golang.org,direct
      - CGO_ENABLED=1
      - TZ=America/Los_Angeles
    devices:
      - /dev/fuse
    device_cgroup_rules:
      - 'b 7:* rmw'
      - 'c 10:237 rmw'
    privileged: true
    working_dir: /workspace
    command: sleep infinity
    volumes:
      - .:/workspace
      - ${GIT_COMMON_DIR}:${GIT_COMMON_DIR}
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
      - pfs-disks:/var/lib/pfs-disks
    ports:
      - '127.0.0.1::40000'
      - '127.0.0.1::40010'
      - '127.0.0.1::40020'
      - '127.0.0.1::8000'

volumes:
  go-mod-cache:
  go-build-cache:
  pfs-disks:
