site_name: PolicyFS
site_description: PolicyFS Documentation
site_url: https://docs.policyfs.org/
repo_url: https://github.com/hieutdo/policyfs
repo_name: hieutdo/policyfs

theme:
  name: material
  palette:
    - media: '(prefers-color-scheme)'
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight

plugins:
  - search

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@11.12.3/dist/mermaid.min.js
  - javascripts/mermaid.js

markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight

nav:
  - Overview: index.md
  - Use cases: use-cases.md
  - Getting started: getting-started.md
  - Guides:
      - Configure: config.md
      - Systemd: systemd.md
      - Disk spindown: spindown.md
      - Troubleshooting: troubleshooting.md
      - FAQ: faq.md
  - Internals:
      - How it works: how-it-works.md
      - Concepts: concepts.md
  - CLI:
      - Overview: cli.md
      - Commands:
          - mount: commands/mount.md
          - unmount: commands/unmount.md
          - index: commands/index.md
          - move: commands/move.md
          - prune: commands/prune.md
          - maint: commands/maint.md
          - doctor: commands/doctor.md
          - version: commands/version.md
