#!/bin/sh
set -eu

if command -v systemctl >/dev/null 2>&1; then
  systemctl stop 'pfs@*.service' >/dev/null 2>&1 || true
  systemctl stop 'pfs-index@*.service' >/dev/null 2>&1 || true
  systemctl stop 'pfs-index@*.timer' >/dev/null 2>&1 || true
fi
